# Generated by Django 4.1.7 on 2023-06-05 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_mycart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyCart",
        ),
    ]
