# Generated by Django 4.1.7 on 2023-05-19 05:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_user_product_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="blog",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="Entry",
        ),
    ]
