# Generated by Django 4.1.7 on 2023-06-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_mycart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mycart",
            name="is_bought",
            field=models.BooleanField(),
        ),
    ]
