# Generated by Django 4.1.7 on 2023-05-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_entry_authors_remove_entry_blog_delete_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productid",
            field=models.IntegerField(default=0),
        ),
    ]
