# Generated by Django 4.1.7 on 2023-06-05 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_mycart_is_bought"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyCart",
        ),
    ]
