# Generated by Django 4.1.7 on 2023-05-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_product_productid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="id",
        ),
        migrations.AlterField(
            model_name="product",
            name="productid",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
