# Generated by Django 4.1.7 on 2023-05-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_remove_product_id_alter_product_productid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="productid",
            field=models.IntegerField(default=0),
        ),
    ]
