# Generated by Django 4.1.7 on 2023-05-19 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_product_id_alter_product_productid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
