# Generated by Django 4.1.7 on 2023-06-06 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_user_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
