# Generated by Django 4.1.7 on 2023-05-19 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
