# Generated by Django 4.1.7 on 2023-07-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_vendorregister"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profileimg",
            field=models.ImageField(default="", upload_to="users"),
        ),
    ]
