# Generated by Django 4.1.7 on 2023-05-19 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_products_delete_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="id",
            new_name="productid",
        ),
    ]
