# Generated by Django 4.1.7 on 2023-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_remove_user_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderDate", models.DateTimeField(auto_created=True, auto_now=True)),
                ("productid", models.CharField(max_length=200)),
                ("productqty", models.CharField(max_length=200)),
                ("userId", models.CharField(max_length=200)),
                ("userName", models.CharField(max_length=200)),
                ("userEmail", models.CharField(max_length=200)),
                ("userContact", models.IntegerField()),
                ("address", models.CharField(max_length=300)),
                ("orderAmount", models.IntegerField()),
                ("paymentMethod", models.CharField(max_length=200)),
                ("transactionId", models.CharField(max_length=200)),
            ],
        ),
    ]
